main : myls.o stat.o                                                                                                                                                               
	gcc -Wall -g -o myls myls.c stat.c
clean :
	rm -rf *.o myls